name: tests

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        environment:
          - py36-pyqt511-ubuntu1804
          - py37-pyqt512-ubuntu2004
          - py38-pyqt514-ubuntu
          - py39-pyqt515-ubuntu
          - py39-pyqt515-windows
        include:
          - environment: py36-pyqt511-ubuntu1804
            python: 3.6
            pyqt: PyQt5>=5.11,<5.12
            platform: ubuntu-18.04
          - environment: py37-pyqt512-ubuntu2004
            python: 3.7
            pyqt: PyQt5>=5.12,<5.13
            platform: ubuntu-20.04
          - environment: py38-pyqt514-ubuntu
            python: 3.8
            pyqt: PyQt5>=5.14,<5.15
            platform: ubuntu-latest
          - environment: py39-pyqt515-ubuntu
            python: 3.9
            pyqt: PyQt5
            platform: ubuntu-latest
          - environment: py39-pyqt515-windows
            python: 3.9
            pyqt: PyQt5
            platform: windows-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - name: Install apt dependencies
        if: ${{ startsWith(matrix.platform, 'ubuntu') }}
        run: |
          sudo apt update
          sudo apt install libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0
          sudo apt install libegl1-mesa libxkbcommon-x11-0
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install Python dependencies
        run: python -m pip install "${{ matrix.pyqt }}" Markdown pymdown-extensions docutils chardet Pygments Markups
      - name: Run tests in Xvfb
        if: ${{ startsWith(matrix.platform, 'ubuntu') }}
        run: xvfb-run -a -s "-screen 0 1024x768x24" python -m unittest discover -s tests -v
      - name: Run tests
        if: ${{ !startsWith(matrix.platform, 'ubuntu') }}
        run: python -m unittest discover -s tests -v
  pyflakes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install Python dependencies
        run: python -m pip install pyflakes
      - name: Run pyflakes
        run: python -m pyflakes ReText/ tests/ setup.py
